config/routes.rb
Rails.application.routes.draw do

  resources :cities
  resources :categories
  resources :posts

  root 'cities#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  has_and_belongs_to_many :cities
end

app/models/city.rb
class City < ActiveRecord::Base
  has_and_belongs_to_many :categories
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @post = Post.new
    @posts = @category.posts.all
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @categories = @city.categories
  end

end

app/controllers/posts_controller.rb
class PostsController<ApplicationController
  
  def create
    @post = Post.create(title: params[:post][:title], content: params[:post][:content], price: params[:post][:price], category_id: params[:category_id])
    redirect_to post_path(@post)
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_new_post.html.erb
<h1>Create a new post and sell some stuff!</h1>

<ul>
  <%= form_for @post do |f| %>
  <li>
    <%= f.label :title  %>
    <%= f.text_field :title  %>
  </li>
  <li>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </li>
  <li>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </li>
  <li>
    <%= f.submit %>
  </li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<ul>
<% if @posts.any? == false %>
  <h1>You need posts</h1>
  <% else %>
  <% @posts.each do |post| %>
  <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
<% end %>
</ul>
<%= render partial: 'posts/new_post' %>

app/views/cities/index.html.erb
<ul>
  <% @cities.each do |city| %>
    <li><%= link_to city.c_name, city_path(city) %></li>
    <% end %>
</ul>

app/views/cities/show.html.erb
<h1><%= @city.c_name %></h1>
<ul>
  <% @categories.each do |category| %>
  <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CraigslistClone</title>
  <h1>Welcome to Britt's List</h1>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_new_post.html.erb
<h1>Create a new post and sell some stuff!</h1>

<ul>
  <%= form_for @post  do |f| %>
  <li>
    <%= f.label :title  %>
    <%= f.text_field :title  %>
  </li>
  <li>
    <%= f.label :content %>
    <%= f.text_area :content %>
    <%= hidden_field_tag :category_id, @category.id %>
  </li>
  <li>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </li>
  <li>
    <%= f.submit  %>
  </li>
  <% end %>
</ul>

app/views/posts/show.html.erb
<%= @post.title %>
<%= @post.content %>
<%= @post.price %>